### ISSUE TITLE
pass-the-bomb Not working properly

### ISSUE THREAD

**Issue by pchauhan77** [NotWoods/pass-the-bomb#2]
This game is not working properly. please fix it and update it.

**Comment by NotWoods** [comment]
Fixed! The README has been updated with new instructions for how to start the program.

**Comment by pchauhan77** [comment]
I want to use video call with this game and deploy to Google app engine how
can I do it?
Please share your email address and WhatsApp no.

Thanks,
Pradeep Chauhan

**Comment by NotWoods** [comment]
Unfortunately I'm not familiar with Google App Engine so I'm not sure how to deploy to it. I'd recommend looking up how to deploy a Node.js program since this is just another Node app. I just tried [deploying to Glitch](https://pass-the-bomb.glitch.me/), which might work for you?

I don't have WhatsApp.

**Comment by pchauhan77** [comment]
is game working properly?
I there any issue?
Can I deploy it to server for testing?

**Comment by NotWoods** [comment]
Yes, the game is working properly. Feel free to deploy it.

**Comment by pchauhan77** [comment]
I want to migrate this code to express.js form hapi.js
How can I do it?
Where I can change the code in which file?

Thanks,
Pradeep Chauhan
